02-Unit2/00-week4-project-wiki/jellyfish-wiki/config/routes.rb
Rails.application.routes.draw do
  resources :jellyfishes
  root 'jellyfishes#index'

  get 'index', to: 'jellyfishes#index'

  get 'about', to: 'static#about'
  get 'faq', to: 'static#faq'

  resources :users
  get 'login', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'
  # add another route to lead to sessions
  resources :sessions, only:[:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/models/jellyfish.rb
class Jellyfish < ApplicationRecord
end

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
# does password hashing using bcrypt gem, and checks if passwords match

  validates :email, presence: true, uniqueness: true
  # email is main point of identification, so must be unique
end

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_action :set_jellyfish, only: [:show, :create, :edit, :update, :destroy]

  # declare methods as helper methods so they are accessible from views
  helper_method :current_user
  helper_method :user_logged_in?
  def current_user
    # @c_user ||= User.find( session[:user_id] ) unless session[:user_id].blank?
    User.find( session[:user_id] ) unless session[:user_id].blank?
  end

  def user_logged_in?
    current_user.present?
  end

  def authenticate_user
    unless user_logged_in?
      flash[:error] = 'Please login first!'
      redirect_to login_url
      # use _url inside controllers and _path in views
    end
  end
end

# def set_jellyfish
#   @jellyfishes = Jellyfish.all
#   @jellyfish = Jellyfish.find(params[:id])
# end

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/controllers/jellyfishes_controller.rb
class JellyfishesController < ApplicationController
  before_action :authenticate_user, only: [:create, :edit, :update, :destroy]
  before_action :set_jellyfish, except: [:index]

  layout 'jellyfishes'

  def index
    @jellyfishes = Jellyfish.all
  end


  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  # def to_param  # overridden
  # name
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jellyfish
      @jellyfishes = Jellyfish.all
      @jellyfish = Jellyfish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jellyfish_params
      params.require(:jellyfish).permit(:name, :scientific_name, :diameter, :lifespan, :rank, :higher_classification, :description, :image)
    end

end

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # session is triggered after user login

  def new
    # $jellyfishes = Jellyfish.all
  end

  def create
    # firstly, find user by email
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      redirect_to root_path, notice: 'Logged In'
    else
      flash.now.alert = 'invalid login details'
      # displays immediately
      render 'new'
      # immediate, not new request
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged Out'
  end
end

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/controllers/static_controller.rb
class StaticController < ApplicationController
  before_action :set_jellyfish

  def about
    # @jellyfishes = Jellyfish.all
  end

  def faq
    # @jellyfishes = Jellyfish.all
  end

end

def set_jellyfish
  @jellyfishes = Jellyfish.all
  # @jellyfish = Jellyfish.find(params[:id])
end

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    $jellyfishes = Jellyfish.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/helpers/application_helper.rb
module ApplicationHelper
end

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/helpers/jellyfishes_helper.rb
module JellyfishesHelper
end

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/helpers/sessions_helper.rb
module SessionsHelper
end

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/helpers/users_helper.rb
module UsersHelper
end

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/views/jellyfishes/_form.html.erb
<%= form_for(jellyfish) do |f| %>
  <% if jellyfish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jellyfish.errors.count, "error") %> prohibited this jellyfish from being saved:</h2>

      <ul>
      <% jellyfish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :scientific_name %>
    <%= f.text_field :scientific_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/views/jellyfishes/_nav.html.erb
<nav class="navbar navbar-default navbar-inverse" style="border-radius:0px;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><span class="glyphicon glyphicon-globe" aria-hidden="true"></span>Bloom.wiki</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <!-- <li class="active"><a href="/">Home <span class="sr-only">(current)</span></a></li> -->
        <li><a href="/about">About</a></li>
        <li><a href="/faq">FAQ</a></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Jellyfishes<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @jellyfishes.each do |jellyfish| %>
            <li><%= link_to jellyfish.name, jellyfish_path(jellyfish) %></li>
            <% end %>
            <!-- <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li> -->
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_logged_in? %>
        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
        <% else %>
        <li><%= link_to 'Login', login_path %></li>
        <% end %>
        <li><a href="/users/new">Sign Up</a></li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/views/jellyfishes/edit.html.erb
<h1>Editing @jellyfish.name</h1>

<%= render 'form', jellyfish: @jellyfish %>

<%= link_to 'Show', @jellyfish %> |
<%= link_to 'Back', jellyfishes_path %>

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/views/jellyfishes/index.html.erb
<link rel="stylesheet" href="https://unpkg.com/flickity@1.2/dist/flickity.min.css">

<script src="https://unpkg.com/flickity@1.2/dist/flickity.pkgd.min.js"></script>

<div class="carousel js-flickity" data-flickity-options='{ "cellAlign": "left", "wrapAround": true, "setGallerySize": false, "autoPlay": 3000, "pauseAutoPlayOnHover": false }'>
  <div class="carousel-cell" style="background-image: url(<%= asset_path('c.jpg') %>)"></div>
  <div class="carousel-cell" style="background-image: url(<%= asset_path('e.jpg') %>)"></div>
  <div class="carousel-cell" style="background-image: url(<%= asset_path('a.jpg') %>)"></div>
  <div class="carousel-cell" style="background-image: url(<%= asset_path('d.jpg') %>)"></div>
  <div class="carousel-cell" style="background-image: url(<%= asset_path('f.jpg') %>)"></div>
  <div class="carousel-cell" style="background-image: url(<%= asset_path('b.png') %>)"></div>
</div>

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/views/jellyfishes/new.html.erb
<h1>New Jellyfish</h1>

<%= render 'form', jellyfish: @jellyfish %>

<%= link_to 'Back', jellyfishes_path %>

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/views/jellyfishes/show.html.erb
<div class="specimen">
  <ul class="list-group col-xs-12 col-md-6 col-md-offset-1">
    <li class="list-group-item specimen-image"><img src="<%= @jellyfish.image %>" class="specimen-image-rounded img-responsive"></li>

    <li class="list-group-item"><h1><%= @jellyfish.name %></h1></li>

    <li class="list-group-item"><p><%= @jellyfish.description %></p></li>
  </ul>

  <ul class="stats list-group col-xs-12 col-md-3 col-md-offset-0">
    <li class="list-group-item"><h5><span class="glyphicon glyphicon-education" aria-hidden="true"></span> Scientific Name</h5> <em><%= @jellyfish.scientific_name %></em></li>

    <li class="list-group-item"><h5><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Higher Classification</h5> <%= @jellyfish.higher_classification %></li>

    <li class="list-group-item"><h5><span class="glyphicon glyphicon-tag" aria-hidden="true"></span> Rank</h5> <%= @jellyfish.rank %></li>

    <li class="list-group-item"><h5><span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span> Diameter</h5> <%= @jellyfish.diameter %></li>
  </ul>
</div>

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloom: A Jellyfish Wiki</title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'jellyfishes/nav' %>
    <%= yield %>
    <% flash.each do |name, message| %>
      <div class="flash-message flash-message-<%= name %>">
        <%= message %> <!-- stored in cookie. adds some persistence -->
      </div>
    <% end %>
  </body>
</html>

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/views/layouts/jellyfish_specimens.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jellyfish Wiki</title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/views/layouts/jellyfishes.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloom: A Jellyfish Wiki</title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #EEEEEE">
    <%= render 'jellyfishes/nav' %>
    <% flash.each do |name, message| %>
      <div class="flash-message flash-message-<%= name %>">
        <%= message %> <!-- stored in cookie. adds some persistence -->
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

02-Unit2/00-week4-project-wiki/jellyfish-wiki/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>