00-Sandbox/pizza-shop/config/routes.rb
Rails.application.routes.draw do
  resources :toppings
  resources :orders
  resources :pizzas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :customers

end

00-Sandbox/pizza-shop/app/models/pizza.rb
class Pizza < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_and_belongs_to_many :toppings
end

00-Sandbox/pizza-shop/app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :set_pizza, only: [:show, :edit, :update, :destroy]

  # GET /pizzas
  # GET /pizzas.json
  def index
    @pizzas = Pizza.all
  end

  # GET /pizzas/1
  # GET /pizzas/1.json
  def show
  end

  # GET /pizzas/new
  def new
    @pizza = Pizza.new
  end

  # GET /pizzas/1/edit
  def edit
  end

  # POST /pizzas
  # POST /pizzas.json
  def create
    @pizza = Pizza.new(pizza_params)

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to @pizza, notice: 'Pizza was successfully created.' }
        format.json { render :show, status: :created, location: @pizza }
      else
        format.html { render :new }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizzas/1
  # PATCH/PUT /pizzas/1.json
  def update
    respond_to do |format|
      if @pizza.update(pizza_params)
        format.html { redirect_to @pizza, notice: 'Pizza was successfully updated.' }
        format.json { render :show, status: :ok, location: @pizza }
      else
        format.html { render :edit }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1
  # DELETE /pizzas/1.json
  def destroy
    @pizza.destroy
    respond_to do |format|
      format.html { redirect_to pizzas_url, notice: 'Pizza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizza
      @pizza = Pizza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pizza_params
      params.require(:pizza).permit(:name, :cheese)
    end
end

00-Sandbox/pizza-shop/app/helpers/pizzas_helper.rb
module PizzasHelper
end

00-Sandbox/pizza-shop/app/views/pizzas/_form.html.erb
<%= form_for(pizza) do |f| %>
  <% if pizza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pizza.errors.count, "error") %> prohibited this pizza from being saved:</h2>

      <ul>
      <% pizza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :cheese %>
    <%= f.check_box :cheese %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

00-Sandbox/pizza-shop/app/views/pizzas/edit.html.erb
<h1>Editing Pizza</h1>

<%= render 'form', pizza: @pizza %>

<%= link_to 'Show', @pizza %> |
<%= link_to 'Back', pizzas_path %>

00-Sandbox/pizza-shop/app/views/pizzas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pizzas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cheese</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pizzas.each do |pizza| %>
      <tr>
        <td><%= pizza.name %></td>
        <td><%= pizza.cheese %></td>
        <td><%= link_to 'Show', pizza %></td>
        <td><%= link_to 'Edit', edit_pizza_path(pizza) %></td>
        <td><%= link_to 'Destroy', pizza, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pizza', new_pizza_path %>

00-Sandbox/pizza-shop/app/views/pizzas/new.html.erb
<h1>New Pizza</h1>

<%= render 'form', pizza: @pizza %>

<%= link_to 'Back', pizzas_path %>

00-Sandbox/pizza-shop/app/views/pizzas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pizza.name %>
</p>

<p>
  <strong>Cheese:</strong>
  <%= @pizza.cheese %>
</p>

<%= link_to 'Edit', edit_pizza_path(@pizza) %> |
<%= link_to 'Back', pizzas_path %>