00-Sandbox/pizza-shop/config/routes.rb
Rails.application.routes.draw do
  resources :toppings
  resources :orders
  resources :pizzas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :customers

end

00-Sandbox/pizza-shop/app/controllers/toppings_controller.rb
class ToppingsController < ApplicationController
  before_action :set_topping, only: [:show, :edit, :update, :destroy]

  # GET /toppings
  # GET /toppings.json
  def index
    @toppings = Topping.all
  end

  # GET /toppings/1
  # GET /toppings/1.json
  def show
  end

  # GET /toppings/new
  def new
    @topping = Topping.new
  end

  # GET /toppings/1/edit
  def edit
  end

  # POST /toppings
  # POST /toppings.json
  def create
    @topping = Topping.new(topping_params)

    respond_to do |format|
      if @topping.save
        format.html { redirect_to @topping, notice: 'Topping was successfully created.' }
        format.json { render :show, status: :created, location: @topping }
      else
        format.html { render :new }
        format.json { render json: @topping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /toppings/1
  # PATCH/PUT /toppings/1.json
  def update
    respond_to do |format|
      if @topping.update(topping_params)
        format.html { redirect_to @topping, notice: 'Topping was successfully updated.' }
        format.json { render :show, status: :ok, location: @topping }
      else
        format.html { render :edit }
        format.json { render json: @topping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /toppings/1
  # DELETE /toppings/1.json
  def destroy
    @topping.destroy
    respond_to do |format|
      format.html { redirect_to toppings_url, notice: 'Topping was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topping
      @topping = Topping.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topping_params
      params.require(:topping).permit(:name)
    end
end

00-Sandbox/pizza-shop/app/helpers/toppings_helper.rb
module ToppingsHelper
end

00-Sandbox/pizza-shop/app/views/toppings/_form.html.erb
<%= form_for(topping) do |f| %>
  <% if topping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topping.errors.count, "error") %> prohibited this topping from being saved:</h2>

      <ul>
      <% topping.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

00-Sandbox/pizza-shop/app/views/toppings/edit.html.erb
<h1>Editing Topping</h1>

<%= render 'form', topping: @topping %>

<%= link_to 'Show', @topping %> |
<%= link_to 'Back', toppings_path %>

00-Sandbox/pizza-shop/app/views/toppings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Toppings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @toppings.each do |topping| %>
      <tr>
        <td><%= topping.name %></td>
        <td><%= link_to 'Show', topping %></td>
        <td><%= link_to 'Edit', edit_topping_path(topping) %></td>
        <td><%= link_to 'Destroy', topping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topping', new_topping_path %>

00-Sandbox/pizza-shop/app/views/toppings/new.html.erb
<h1>New Topping</h1>

<%= render 'form', topping: @topping %>

<%= link_to 'Back', toppings_path %>

00-Sandbox/pizza-shop/app/views/toppings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @topping.name %>
</p>

<%= link_to 'Edit', edit_topping_path(@topping) %> |
<%= link_to 'Back', toppings_path %>